version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/copy_files.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/restart_nginx.sh
      timeout: 100
      runas: root
