version: 0.2

phases:
  install:
     runtime-versions:
       nodejs: latest
  pre_build:
    commands:
      - echo Build started 
  build:
    commands:
      - echo Building wechat_backend:v1.1
      - cd sd_page
      - mkdir sd_page_build
      - npm install
      - npm run build
  post_build:
    commands:
      - echo Build completed
      - cp -r ./build/* ./sd_page_build/
      - mv ../appspec.yml sd_page_build/
      - mv ../kupotech.com.cn.pem sd_page_build/
      - mv ../kupotech.com.cn.key sd_page_build/
      - ls -la ../
      - cp ../scripts sd_page_build/
      - cd sd_page_build
      - zip -r ../../sd_page_build.zip  *
      - cd ..
artifacts:
  files: 
    - 'sd_page_build.zip'