version: 0.2

phases:
  install:
     runtime-versions:
       nodejs: latest
  pre_build:
    commands:
      - echo Build started 
  build:
    commands:
      - echo Building wechat_backend:v1.1
      - cd sd_page
      - npm install
      - npm run build
      - cp -r ./build/* ./sd_page_build/
  post_build:
    commands:
      - echo Build completed
artifacts:
  files: 
    - '/sd_page/sd_page_build/**/*'